{"name": "test_001[1-3-5]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (1 + 3) == 5", "trace": "self = <test_01.Test_demo object at 0x00000141C51B1E80>, a = 1, b = 3, excepted = 5\n\n    @pytest.mark.parametrize(\"a,b,excepted\",[(1,3,5),(2,3,4),(3,6,9)])\n    def test_001(self,a,b,excepted):\n    \n>       assert a+b == excepted\nE       assert (1 + 3) == 5\n\ntest_01.py:27: AssertionError"}, "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "3"}, {"name": "excepted", "value": "5"}], "start": 1566804875883, "stop": 1566804875884, "uuid": "ec1ff7b0-36c3-457c-9d79-4d51fcdf3717", "historyId": "e5c6b0e987ac5bb2c6c98e8099607e96", "testCaseId": "c54d119d4f0898340c96dbdbc1466b76", "fullName": "test_01.Test_demo#test_001", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_01"}, {"name": "subSuite", "value": "Test_demo"}, {"name": "host", "value": "work-limeng"}, {"name": "thread", "value": "91608-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01"}]}