{"name": "test_002[3-6-9]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (3 - 6) == 9", "trace": "self = <test_01.Test_demo object at 0x00000141C51B8400>, a = 3, b = 6, excepted = 9\n\n    @pytest.mark.parametrize(\"a,b,excepted\",[(4,3,5),(2,3,4),(3,6,9)])\n    def test_002(self,a,b,excepted):\n>       assert a-b == excepted\nE       assert (3 - 6) == 9\n\ntest_01.py:31: AssertionError"}, "parameters": [{"name": "a", "value": "3"}, {"name": "b", "value": "6"}, {"name": "excepted", "value": "9"}], "start": 1566804876074, "stop": 1566804876075, "uuid": "aab9464c-4c99-4686-b62b-c5e04b818afe", "historyId": "fd0a43d23ecd2ce9412ac3685487cf92", "testCaseId": "18dfd4a6aa36e9381a16ace47dfec8d6", "fullName": "test_01.Test_demo#test_002", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_01"}, {"name": "subSuite", "value": "Test_demo"}, {"name": "host", "value": "work-limeng"}, {"name": "thread", "value": "91608-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01"}]}