{"name": "test_one", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'a' in 'iphone'", "trace": "self = <test_01.TestClassTwo object at 0x000002B27FCCAAC8>\n\n    def test_one(self):\n        x = \"iphone\"\n>       assert 'a'in x\nE       AssertionError: assert 'a' in 'iphone'\n\ntest_01.py:10: AssertionError"}, "start": 1566802351237, "stop": 1566802351237, "uuid": "bd04978c-7c10-40e8-84e5-1a242107c0b6", "historyId": "3c4dcdaac768f18a1ceaf96180ce0618", "testCaseId": "5a78baa655fd95e91f3065b338e94225", "fullName": "test_01.TestClassTwo#test_one", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_01"}, {"name": "subSuite", "value": "TestClassTwo"}, {"name": "host", "value": "work-limeng"}, {"name": "thread", "value": "76580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01"}]}