{"name": "test_001[2-3-4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (2 + 3) == 4", "trace": "self = <test_01.Test_demo object at 0x00000141C51B19E8>, a = 2, b = 3, excepted = 4\n\n    @pytest.mark.parametrize(\"a,b,excepted\",[(1,3,5),(2,3,4),(3,6,9)])\n    def test_001(self,a,b,excepted):\n    \n>       assert a+b == excepted\nE       assert (2 + 3) == 4\n\ntest_01.py:27: AssertionError"}, "parameters": [{"name": "a", "value": "2"}, {"name": "b", "value": "3"}, {"name": "excepted", "value": "4"}], "start": 1566804875959, "stop": 1566804875960, "uuid": "683a34ca-243d-4874-b45e-68e9670adc33", "historyId": "005d319ea0efd3226f4840bebab9011b", "testCaseId": "c54d119d4f0898340c96dbdbc1466b76", "fullName": "test_01.Test_demo#test_001", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_01"}, {"name": "subSuite", "value": "Test_demo"}, {"name": "host", "value": "work-limeng"}, {"name": "thread", "value": "91608-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01"}]}