{"name": "test_002[2-3-4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (2 - 3) == 4", "trace": "self = <test_01.Test_demo object at 0x00000141C518CBA8>, a = 2, b = 3, excepted = 4\n\n    @pytest.mark.parametrize(\"a,b,excepted\",[(4,3,5),(2,3,4),(3,6,9)])\n    def test_002(self,a,b,excepted):\n>       assert a-b == excepted\nE       assert (2 - 3) == 4\n\ntest_01.py:31: AssertionError"}, "parameters": [{"name": "a", "value": "2"}, {"name": "b", "value": "3"}, {"name": "excepted", "value": "4"}], "start": 1566804876041, "stop": 1566804876042, "uuid": "419c8179-5c50-4750-955c-0b872546a59c", "historyId": "c0fc26118fc76a8dc758c6509ef4b9a4", "testCaseId": "18dfd4a6aa36e9381a16ace47dfec8d6", "fullName": "test_01.Test_demo#test_002", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_01"}, {"name": "subSuite", "value": "Test_demo"}, {"name": "host", "value": "work-limeng"}, {"name": "thread", "value": "91608-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01"}]}