{"name": "test_002[4-3-5]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (4 - 3) == 5", "trace": "self = <test_01.Test_demo object at 0x00000141C518C828>, a = 4, b = 3, excepted = 5\n\n    @pytest.mark.parametrize(\"a,b,excepted\",[(4,3,5),(2,3,4),(3,6,9)])\n    def test_002(self,a,b,excepted):\n>       assert a-b == excepted\nE       assert (4 - 3) == 5\n\ntest_01.py:31: AssertionError"}, "parameters": [{"name": "a", "value": "4"}, {"name": "b", "value": "3"}, {"name": "excepted", "value": "5"}], "start": 1566804876005, "stop": 1566804876005, "uuid": "c0528824-9728-4e0a-b75f-dda2c2571834", "historyId": "7a9e0cf3014c208362c7733da2a013f8", "testCaseId": "18dfd4a6aa36e9381a16ace47dfec8d6", "fullName": "test_01.Test_demo#test_002", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_01"}, {"name": "subSuite", "value": "Test_demo"}, {"name": "host", "value": "work-limeng"}, {"name": "thread", "value": "91608-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01"}]}